
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/jquery.flashSlider-1.0.min.js" type="text/javascript"></script>
<div class="main">
	<div style="height:850px;width:791px;background-color:#fcdf95;padding:10px;border-left:2px solid #5e3929;border-right:2px solid #5e3929;border-bottom:2px solid #5e3929;">
		<div style="height:850px;background-color:#FFEBCD;">
<!--		<div style="margin-top:30px;margin-left:6px;"><img src="{%$staticUrl%}/alchemy/image/pay/pay2.jpg" /></div>-->
	<ul>
	<!-- <li style="margin-left:75px; font-size:14px;padding-top:5px;">
		首次充值100宝石，可获入门礼包，含金币5000，HP急救箱2个 
	</li>
	<li style="margin-left:75px; font-size:14px;padding-top:5px;">
		首次充值500宝石，可获进阶礼包，含金币7000，HP急救箱5个，LV16项链翡翠之心
	</li>
	<li style="margin-left:75px; font-size:14px;padding-top:5px;">
		首次充值1000宝石，可获高手礼包，含金币10000，HP急救箱10个，LV26钻石之心，传奇精灵弓手“琳”
	</li>
	<li style="margin-left:75px; font-size:14px;padding-top:5px;">
		首次充值5000宝石，可获大神礼包，含金币20000，HP急救箱15个，LV31辉煌之心，传奇人类战士“铁锤十四世”
	</li>-->
	
	<!-- test http://open.weibo.com/paytest/payTestPay.php -->
	<!-- http://pay.weibo.com/wb/?c=pay -->
	{% if $appServerTtpe == '1' %}
		<form id="frmPayOrder" method="post" action="http://pay.weibo.com/wb/?c=pay" target="_top" style="display:none;">
	{% else %}
		<form id="frmPayOrder" method="post" action="http://open.weibo.com/paytest/payTestPay.php" target="_top" style="display:none;">
	{% /if %}
	
		<input type="hidden" id="return_url" name="return_url" value="http://game.weibo.com/{%$smarty.const.APP_NAME%}/" />
		<input type="hidden" id="order_id" name="order_id" value="" />
		<input type="hidden" id="order_uid" name="order_uid" value="{%$platformUid%}" />
		<input type="hidden" id="desc" name="desc" value="" />
		<input type="hidden" id="appkey" name="appkey" value="{%$smarty.const.APP_ID%}"  />
		<input type="hidden" id="amount" name="amount" value="" />
		<input type="hidden" id="version" name="version" value="1.0" />
		<input type="hidden" id="token" name="token" value="" />
	</form>
	
	</ul>
	{% foreach from=$section key=k item=v %}
	{% if $v.open == 1 %}
				<div class="chongzhi">
					<div class="chongzhi-bg">
					<div class="chongzhi-ed"><img src="{%$staticUrl%}/alchemy/image/pay/{%$v.gold.img%}" title="{%$v.gold.title%}" /></div>
	{% foreach from=$v.include item=v2 %}
	{% if $v2.cid>0 && $v2.num>0 %}
						<div class="chongzhi-item">
	{% if $v2.limit == 1 %}
	                    	<div class="xian"><img src="{%$staticUrl%}/alchemy/image/pay/timelimit.gif" /></div>
	{% /if %}
							<img src="{%$staticUrl%}/alchemy/image/pay/include/item/{%$v2.cid%}-{%$v2.num%}.png" />
							
						</div>
	{% /if %}
	{% /foreach %}
					</div>
					<div class="chongzhi-bt"><img class="diamond" src="{%$staticUrl%}/alchemy/image/pay/{%$v.btn.img%}" onclick="payOrder({%$v.id%});return false;" /></div>
				</div>
	{% /if %}
	{% /foreach %}
			<div class="clear"></div>
		    <div class="xianshi" style="width:720px;height:20px;clear:both;margin-left:40px;padding-top:15px;">
		    	{%$note%}
		    </div>
			<div style="color:grey;padding:20px 10px 20px 40px;">
				友情小提示：成功充值后宝石即刻到账，部分用户可能因为网络原因，宝石约10分钟左右到帐！<br/>
				客服提示：如果有支付相关的疑问，请<a href="http://game.weibo.com/club/showsubjectList?groupId=249" target="_blank">点击这里</a>，或者私信<a href="http://weibo.com/yongzzelong" target="_blank">勇者战恶龍官方微博</a>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    function payOrder(type)
    {
        if (type<1 || type>4) {
			return false;
        }

    	$.ajax({
        	type: 'post',
			url: '{%$baseUrl%}/paysinawb/order',
			data: 'type='+type,
			dataType: 'json',
			success:function(data){
				/*alert(data);
    			$.each(data, function(i, n){
        	    	alert( "Item #" + i + ": " + n );
        	    });*/

				if(data != '' && data.info && data.status==1) {
					$('#order_id').val(data.info.order_id);
					$('#desc').val(data.info.desc);
					$('#amount').val(data.info.amount);
					//$('#amount').val('1');
                	$('#token').val(data.info.token);
                	$('#frmPayOrder').submit();
				} else{
					alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
					setBtnEnable(true);
				}
			},
			error:function(){
				alert("[出现错误啦]: 暂时无法提交订单，请稍后重试。");
				setBtnEnable(true);
			}
		});
		
    	return true;
    }

</script>