<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<!--[if lt IE 7]><![endif]-->
	<link rel="stylesheet" type="text/css" href="{%$staticUrl%}/admin/css/admin.css" media="screen" />
	<script type="text/javascript" src="{%$staticUrl%}/admin/js/jquery-1.5.2.min.js"></script>
	<title>{%$appTitle%}后台管理</title>
</head>

<body id="admin">