<div style="background:#e3eef8;margin:0px;padding:5px 0px;border:2px solid #cee1ee;margin-top:5px;margin-bottom:5px;width:812px;align:center;text-align:center;font-weight:bold;">
【炼金大冒险】由上海乐之鲸鱼数码科技有限公司提供技术支持&nbsp;&nbsp;用户ID号: {%$uid%}<span id="userinfo" style="color:red;"></span>&nbsp;&nbsp;<a href="javascript:addFavor();"><img src="{%$staticUrl%}/alchemy/image/common/favorite.png" style="top:5px;position:relative;padding-right:8px;" /></a>
<br/>
<br/>
若您在游戏中遇到问题，请<a href="http://www.kaixin001.com/group/topic.php?gid=1091430&tid=42926309" target="_blank">点击这里</a>，或者联系游戏客服QQ：2414377107，欢迎加入玩家QQ群：184010533</a>
<br/>
<br/>
健康游戏忠告：抵制不良游戏，拒绝盗版游戏    注意自我保护，谨防受骗上当    适度游戏益脑，沉迷游戏伤身    合理安排时间，享受健康生活
</div>

<iframe width="816" height="176" frameborder="0" scrolling="no" src="{%$staticUrl%}/alchemy/html/b/index.html?v=2012070102"></iframe>
<div id="faq" style="position:absolute; top:92px; left:150px; display:none;">
<span style="font-size:30px;color:red; font-weight:bolder; cursor:pointer; position:absolute;left:740px;" onclick="hidefaq();">×</span>
<iframe  width="816" height="600" frameborder="0" scrolling="no" src="{%$hostUrl%}/faq/index?uid={%$uid%}" ></iframe>
</div>
<script src="http://s.kaixin001.com.cn/js/openapp-8.js" language="javascript"></script>
<script type="text/javascript">
function addFavor()
{
	var url = "http://www.kaixin001.com/!app_alchemy/";
	var title = "炼金大冒险-开心网";
	if (document.all) {
		window.external.AddFavorite( url, title);
	} else if (window.sidebar) {
		window.sidebar.addPanel(title, url,"");
	} else if (window.opera && window.print) {
		var mbm = document.createElement('a');
		mbm.setAttribute('rel','sidebar');
		mbm.setAttribute('href',url);
		mbm.setAttribute('title',title);
		mbm.click();
	} else {
		alert("浏览器不支持直接加入收藏夹，请手动添加。");
	}
}

function openInvitationDlg()
{
	var p = {"app_id":100036352,"display":"iframe","redirect_uri":"{%$hostUrl%}/callback","text":"剑与魔法的世界，各方势力暗潮涌动，纷争再起！屌丝青年如何炼成高帅富！探险、佣兵、收集、炼金！搞钱，搞怪，搞装备！"};
    p.cb = function(v){if(window.console)console.log(v);};
    KX.invitation(p);
    return false;
}
function showfaq()
{
	$('#flashdiv').css('left', -9999);
	$('#faq').show();
	$('#faq').height(600);
}

function hidefaq()
{
	$('#flashdiv').css('left', 0);
	$('#faq').hide();
	$('#faq').height(0);
}
</script>

{% if $smarty.const.APP_SERVER_TYPE == 1 %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33297048-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% /if %}
