{%include file="hapyfishadmin/header.phtml"%}
<style type="text/css">
<!--
table{font-size:14px;border-collapse: collapse;border-spacing: 0;empty-cells: show;}
th, td {border: 1px solid #B1CBE2;}
th{background-color: #D5E7F3;}
td{padding:2px;}
.odd{background-color: #EAF2F5;}
.total{font-weight:bold;}

-->
</style>
	<h1>后台管理</h1>
	<ul id="nav">
		<li><a href="{%$baseUrl%}/swhadmin">首页</a></li>
		<li><a href="{%$baseUrl%}/swhadmin/timegift">时间礼包管理</a></li>
		<li><a href="{%$baseUrl%}/swhadmin/levelgift">等级礼包管理</a></li>
		<li><a href="{%$baseUrl%}/swhadmin/sevengift">七天礼包管理</a></li>
		<li><a href="{%$baseUrl%}/swhadmin/package">礼包管理</a></li>
		<li><a href="{%$baseUrl%}/swhadmin/daliytask">日常任务</a></li>
		<li><a href="{%$baseUrl%}/swhadmin/guild">公会</a></li>
		<li>当前登录者：{%$adminName%}</li>
	</ul>

	<div id="container">
		<strong>战士礼包</strong>
		注：礼包内容[661,3,1,4] 分别为cid type num 品质  type分类：1金币，2宝石，3装备道具，4佣兵。（只有装备有品质属性，其他没有为[121,3,1]）
		<div id="divedit">
		<table >
		<tr>
		<th>等级</th><th>下一等级</th><th>礼包内容</th><th>操做</th>
		</tr>
		<tr><td><input id="id_1" name="id" size=8 /></td>
		<td><input id="nextId_1" name="next_id" size=8 /></td>
		<td><input id="list_1" name="list" size=38 /></td>
		<td><input type="button"  onclick="add(1);" value="添加"/>
		</tr>
		</table>
		<table >
		<tr>
			<th>等级</th><th>下一等级</th><th>礼包内容</th><th>操做</th>
		</tr>
		{% foreach from=$zhanshi item=data %}
		<tr><td><input id="{%$data.level%}_id_1" value="{%$data.level%}" size=8 /></td>
		<td><input id="{%$data.level%}_nextId_1" value="{%$data.nextLevel%}" size=8 /></td>
		<td><input id="{%$data.level%}_list_1" value="{%$data.awards%}" size=38 /></td>
		<td><input type="button"  onclick="update({%$data.level%},1);" value="修改"/><input type="button" onclick="deletel({%$data.level%},1);" value="删除"/></td>
		</tr>
		{% /foreach  %}
		</table>
		<br />
		<br />
		<strong>弓手礼包</strong>
		<table >
		<tr>
		<th>等级</th><th>下一等级</th><th>礼包内容</th><th>操做</th>
		</tr>
		<tr><td><input id="id_2" name="id" size=8 /></td>
		<td><input id="nextId_2" name="next_id" size=8 /></td>
		<td><input id="list_2" name="list" size=38 /></td>
		<td><input type="button"  onclick="add(2);" value="添加"/>
		</tr>
		</table>
		<table >
		<tr>
			<th>等级</th><th>下一等级</th><th>礼包内容</th><th>操做</th>
		</tr>
		{% foreach from=$gongshou item=data %}
		<tr><td><input id="{%$data.level%}_id_2" value="{%$data.level%}" size=8 /></td>
		<td><input id="{%$data.level%}_nextId_2" value="{%$data.nextLevel%}" size=8 /></td>
		<td><input id="{%$data.level%}_list_2" value="{%$data.awards%}" size=38 /></td>
		<td><input type="button"  onclick="update({%$data.level%},2);" value="修改"/><input type="button" onclick="deletel({%$data.level%},2);" value="删除"/></td>
		</tr>
		{% /foreach  %}
		</table>
		<br />
		<br />
		<strong>法师礼包</strong>
		<table >
		<tr>
		<th>等级</th><th>下一等级</th><th>礼包内容</th><th>操做</th>
		</tr>
		<tr><td><input id="id_3" name="id" size=8 /></td>
		<td><input id="nextId_3" name="next_id" size=8 /></td>
		<td><input id="list_3" name="list" size=38 /></td>
		<td><input type="button"  onclick="add(3);" value="添加"/>
		</tr>
		</table>
		<table >
		<tr>
			<th>等级</th><th>下一等级</th><th>礼包内容</th><th>操做</th>
		</tr>
		{% foreach from=$fashi item=data %}
		<tr><td><input id="{%$data.level%}_id_3" value="{%$data.level%}" size=8 /></td>
		<td><input id="{%$data.level%}_nextId_3" value="{%$data.nextLevel%}" size=8 /></td>
		<td><input id="{%$data.level%}_list_3" value="{%$data.awards%}" size=38 /></td>
		<td><input type="button"  onclick="update({%$data.level%},3);" value="修改"/><input type="button" onclick="deletel({%$data.level%},3);" value="删除"/></td>
		</tr>
		{% /foreach  %}
		</table>
		</div>
	</div><!--/#container-->
	<script type="text/javascript">
	function add(type) {
		var id = $("#id_"+type).val();
		var next_id = $("#nextId_"+type).val();
		var list = $("#list_"+type).val();
		$.ajax({
            type: 'POST',
            url: '/swhadmin/addl',
            data: {'type': type,'id':id,'next_id':next_id,'list':list},
            dataType: 'text',
            success: function(resp){
            	location.reload(true);  
            },
    		error: function(resp){
    		},
    		complete: function(resp){
    		}
 		});
		
	}

	function update(id,type) {
		var id = $("#"+id+"_id_"+type).val();
		var next_id = $("#"+id+"_nextId_"+type).val();
		var list = $("#"+id+"_list_"+type).val();
		$.ajax({
            type: 'POST',
            url: '/swhadmin/addl',
            data: {'type': type,'id':id,'next_id':next_id,'list':list},
            dataType: 'text',
            success: function(resp){
            	location.reload(true);  
            },
    		error: function(resp){
    		},
    		complete: function(resp){
    		}
 		});
		
	}

	function deletel(id,type) {
		$.ajax({
            type: 'POST',
            url: '/swhadmin/deletel',
            data: {'type': type,'id':id},
            dataType: 'text',
            success: function(resp){
            	location.reload(true);  
            },
    		error: function(resp){
    		},
    		complete: function(resp){
    		}
 		});
		
	}
	
	</script>
{%include file="hapyfishadmin/footer.phtml"%}