<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{%$staticUrl%}/alchemy/feed.css?v=1.04" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<title>炼金客服</title>
<style type="text/css">
body{font:12px/1.5 Arial, Helvetica, sans-serif; background:#ffffff; color:#666;}
body,ul,li{margin:0; padding:0;}
li{float:left; margin-left:5px; font-size:14px; color:#000000;}
a{text-decoration:none; color:#666666;}
img{border:none;}
img,input{vertical-align:middle;}
td{border-bottom:#d5e7f3 1px solid ;}
ul li{list-style:none;}
</style>
</head>
<body>
<!-- ClickTale Top part -->
<script type="text/javascript">
var WRInitTime=(new Date()).getTime();

</script>
<!-- ClickTale end of Top part -->
<div class="z-m z-w74" style="margin-top:20px;">
<div class="b8">
	<div class="height8"></div>
	<div>
		
    	<a href="{%$hostUrl%}/faq/index?uid={%$uid%}">
    		<div class="tab_p7a">提交问题</div>
    	</a>
    	<div class="w20"></div>
    	<a href="{%$hostUrl%}/faq/myfaq?uid={%$uid%}">
    	<div class="tab_p6a">我的问题</div>
    	</a>
    	<div class="w480"></div>
  	</div>
  	<ul class="p6">
		
	</ul>
  	
    <div class="height4"></div>
	<div>
	<ul>
	<li><a href="{%$hostUrl%}/faq/myfaq?uid={%$uid%}">问题列表</a></li>
	<li>></li>
	<li>问题详情</li>
	</ul>
  	</div>
  	<ul class="p6">
		
	</ul>
  	
    <div class="height4"></div>
    

    
  	<div style="clear:both;"></div>
  	<div style="width:740px;height:500px; overflow-y:auto;">
  	<div style="border-bottom: 1px dashed #D0D0D0; margin-bottom: 20px;">
  	<div style="font-size:18px;font-weight:bold;padding:5px;background-color:#d5e7f3;">{%$data.title%}</div>
  	<div style="padding:5px;">问题id:&nbsp;{%$data.id%}&nbsp;&nbsp;&nbsp;提问时间:&nbsp;{%$data.create_time|date_format:"%Y-%m-%d %H:%M:%S"%}</div>
  	<div style="padding:5px;font-size:16px;">{%$data.content%}</div>
  	</div>
  	<div><span style="font-size:18px;font-weight:bold; float:left;">回答:</span><span style="font-size:14px; float:left;margin-left:10px;color:#999999;line-height:30px;">本回复由“炼金大冒险”客服解答</span></div>
  	<div style="clear:both;"></div>
  	<div style="padding:20px;color:#000000;height:300px;width:690px;background-color:#d5e7f3;font-size:14px;border:0px;">{%$data.answer%}</div>
  	
</div>
</div>
</div>
<!-- ClickTale Bottom part -->
<div id="ClickTaleDiv" style="display: none;"></div>
{% if $smarty.const.APP_SERVER_TYPE == 1 %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33297048-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% /if %}
</body>
