<div class="title" style="position:relative;">
	<div class="menu">
        <ul style="padding-left:145px;width:815px;">
        	<li id="home" alt="进入游戏"><a href="javascript:void(0);" onclick="enterGame();"></a></li>
        	<li id="invite" alt="邀请好友"><a href="javascript:void(0);" onclick="return openInvitationDlg();"></a></li>
        	<li id="pay" alt="充值兑换 "><a href="javascript:void(0);"></a></li>
        	<li id="page" alt="最新活动"><a href="http://www.kaixin001.com/group/topic.php?gid=1091430&tid=43164999" target="_blank"></a></li>
        	<li id="forum" alt="玩家论坛"><a href="http://www.kaixin001.com/group/group.php?gid=1091430" target="_blank"></a></li>
        	<li id="faqm" alt="问题反馈 "><a href="javascript:void(0);" onclick="showfaq();"></a></li>
        </ul>
	</div>
{% if $showNotice == true %}
<div id="notice" style="position:absolute;left:190px;top:65px;width:520px;height:16px;overflow:hidden;">
<ul>
{% foreach from=$notice item=data %}
<li>{%if $data.link%}<a href="{%$data.link%}" target="_blank">[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}</a>{%else%}[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}{%/if%}</li>
{% /foreach %}
</ul>
<script type="text/javascript">
function autoScroll(obj)
{
$(obj).find("ul:first").animate({
	marginTop:"-16px"
	},500,function(){
		$(this).css({marginTop:"0px"}).find("li:first").appendTo(this);
	});
}
$(document).ready(function(){
	setInterval('autoScroll("#notice")',10000)
});
</script>
</div>
{% /if %}
</div>