<div style="width:100%;background:#e3eef8;border:2px solid #cee1ee;">
<div style="background:#e3eef8;margin:auto;padding:5px 0px;margin-top:5px;margin-bottom:5px;width:810px;align:center;text-align:center;font-weight:bold;">
【勇者战恶龍】由上海乐之鲸鱼数码科技有限公司提供技术支持&nbsp;&nbsp;用户ID号: {%$uid%}<span id="userinfo" style="color:red;"></span>&nbsp;&nbsp;<a href="javascript:addFavor();"><img src="{%$staticUrl%}/alchemy/image/common/favorite.png" style="top:5px;position:relative;padding-right:8px;" /></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://game.weibo.com/home/user/authInput" target="_blank">防沉迷认证</a>
<br/>
<br/>
若您在游戏中遇到问题，请<a href="http://game.weibo.com/club/showsubjectList?groupId=249" target="_blank">点击这里</a>，或者私信<a href="http://weibo.com/yongzzelong" target="_blank">勇者战恶龍官方微博</a>。
<br/>
<br/>
健康游戏忠告：抵制不良游戏，拒绝盗版游戏    注意自我保护，谨防受骗上当    适度游戏益脑，沉迷游戏伤身    合理安排时间，享受健康生活
</div>
</div>
<div id="faqBox" style="width:815px;height:705px;position:absolute;background-color:#FFFFFF;top:92px;border:2px solid #ffffff;display:none;margin:auto;">
 <div style="color:blue;position:absolute;left:752px;top:2px;"><a id="faqClose" href="javascript:void(0);"><img src="{%$staticUrl%}/alchemy/image/common/btnClose.png" /></a></div>
<div id="divFaq" style=""></div>
</div>
<div id="payBox" style="width:815px;height:1200px;position:absolute;background-color:#FFFFFF;top:92px;display:none;margin:auto;">
    <div style="color:blue;position:absolute;left:752px;top:2px;"><a id="payClose" href="javascript:void(0);"><img src="{%$staticUrl%}/alchemy/image/common/btnClose.png" /></a></div>
    <div id="divPay" style=""></div>
</div>
<div id="inviteBox" style="width:815px;height:1200px;position:absolute;background-color:#FFFFFF;top:92px;display:none;margin:auto;">
    <div style="color:blue;position:absolute;left:752px;top:2px;"><a id="inviteClose" href="javascript:void(0);"><img src="{%$staticUrl%}/alchemy/image/common/btnClose.png" /></a></div>
	<div id="divInvite" style=""></div>
</div>
<div id="helpBox" style="width:815px;height:1200px;position:absolute;background-color:#FFFFFF;top:92px;display:none;margin:auto;">
    <div style="color:blue;position:absolute;left:752px;top:2px;"><a id="helpClose" href="javascript:void(0);"><img src="{%$staticUrl%}/alchemy/image/common/btnClose.png" /></a></div>
    <div id="divHelp" style=""></div>
</div>
<div style="display:none;"><img src="http://monitor.happyfishgame.com.cn/img/10.jpg"/><img src="http://monitor.happyfishgame.com.cn/img/200.jpg"/></div>

<div style="margin:auto;width:816px;"><iframe width="816" height="176" frameborder="0" scrolling="no" src="{%$staticUrl%}/alchemy/html/b/index.html?v=2012070102"></iframe></div>
<div id="faq" style="position:absolute;top:92px;display:none;">
<input type="button"  onclick="hidefaq();" class="hidefaq" />
<iframe  width="816" height="600" frameborder="0" scrolling="no" src="{%$hostUrl%}/faq/index?uid={%$uid%}" ></iframe>
</div>

{% if $platform == "sinaweibo" %}
{%include file="cmscript_sinawb.phtml"%}
{% else %}

{% /if %}

<script src="{%$staticUrl%}/alchemy/js/payment.js?v=1.0.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function() {
	var config = {appId:'{%$smarty.const.APP_ID%}', appName:'{%$smarty.const.APP_NAME%}', appHostUrl:'{%$hostUrl%}', appStaticUrl:'{%$staticUrl%}',
            	  sns:'kaixin001', uid:'{%$uid%}', puid:'{%$platformUid%}', sessionkey:'{%$skey%}', sessionid:'{%$sessionid%}'};
	HFApp.init(config);
	$("#pay").unbind('click');
    $("#pay").click(showPay);
    $("#payClose").click(hidePay);

	$("#invite").unbind('click');
    $("#invite").click(showInvite);
    $("#inviteClose").click(hideInvite);

    $("#help").unbind('click');
    $("#help").click(showHelp);
    $("#helpClose").click(hideHelp);
    
    $("#faqm").unbind('click');
    $("#faqm").click(showfaq);
    $("#faqClose").click(hidefaq);
    //
    //HFApp.backendReq(['restapi/appinvited']);

    //var payConfig = {userId:"{%$uid%}",platformUid:"{%$platformUid%}",staticUrl:"{%$staticUrl%}",payOrderUrl:"{%$hostUrl%}/pay/order"};
    //var payLang = {error:"验证失败,请重新验证。"}; 
    //Hapyfish.Payment.init(payLang, payConfig);
});

function addFavor()
{
	var url = "http://game.weibo.com/dragons/";
	var title = "勇者战恶龍-新浪微游戏";
	if (document.all) {
		window.external.AddFavorite( url, title);
	} else if (window.sidebar) {
		window.sidebar.addPanel(title, url,"");
	} else if (window.opera && window.print) {
		var mbm = document.createElement('a');
		mbm.setAttribute('rel','sidebar');
		mbm.setAttribute('href',url);
		mbm.setAttribute('title',title);
		mbm.click();
	} else {
		alert("浏览器不支持直接加入收藏夹，请手动添加。");
	}
}

/** pay **/
function showPay()
{
	//hidePay();
	hideInvite();
	hideHelp();
	hidefaq();
	
	var url = HFApp.appHostUrl + "/paysinawb";
	
	var pardata = {};
	HFApp.loadHtml(url, 'POST', pardata, 'text', 'divPay');
	$('#flashdiv').css('left', -9999);
	$('#main_content').css('left', -9999);
	
	//$("#payBox").toggle('fast');
	$('#payBox').show();
}

function hidePay()
{
	$('#flashdiv').css('left', 0);
	$('#main_content').css('left', 0);
	//$("#payBox").toggle('fast');
	$('#payBox').hide();
}

function showFaq()
{
	hidePay();
	hideInvite();
	hideHelp();
	
	var url = HFApp.appHostUrl + "/faq";
	
	var pardata = {};
	HFApp.loadHtml(url, 'POST', pardata, 'text', 'divFaq');
	$('#flashdiv').css('left', -9999);
	$('#main_content').css('left', -9999);
	
	//$("#payBox").toggle('fast');
	$('#faqBox').show();
}

function hideFaq()
{
	$('#flashdiv').css('left', 0);
	$('#main_content').css('left', 0);
	//$("#payBox").toggle('fast');
	$('#faqBox').hide();
}




/** pay **/


/** invite **/

function openInvitationDlg()
{
	showInvite();
}


function showInvite()
{
	hidePay();
	//hideInvite();
	hideHelp();
	hidefaq();
	
	var url = HFApp.appHostUrl + "/invitesinawb";
	var pardata = {};
	HFApp.loadHtml(url, 'POST', pardata, 'text', 'divInvite');
	$('#flashdiv').css('left', -9999);
	$('#main_content').css('left', -9999);
	//$("#inviteBox").toggle('fast');
	$('#inviteBox').show();
}

function hideInvite()
{
	$('#flashdiv').css('left', 0);
	$('#main_content').css('left', 0);
	//$("#inviteBox").toggle('fast');
	$('#inviteBox').hide();
}

function showHelp()
{
	hidePay();
	hideInvite();
	//hideHelp();
	hidefaq();
	
	var url = HFApp.appHostUrl + "/help";
	var pardata = {};
	HFApp.loadHtml(url, 'POST', pardata, 'text', 'divHelp');
	$('#flashdiv').css('left', -9999);
	$('#main_content').css('left', -9999);

	//$("#helpBox").toggle('fast');
	$('#helpBox').show();
}

function hideHelp()
{
	$('#flashdiv').css('left', 0);
	$('#main_content').css('left', 0);
	//$("#helpBox").toggle('fast');
	$('#helpBox').hide();
}
/** invite **/

function showfaq()
{
	hidePay();
	hideInvite();
	hideHelp();
	//hidefaq();
	
	$('#flashdiv').css('left', -9999);
	$('#main_content').css('left', -9999);
	
	$('#faq').show();
	$('#faq').height(600);
}

function hidefaq()
{
	$('#flashdiv').css('left', 0);
	$('#main_content').css('left', 0);
	$('#faq').hide();
	$('#faq').height(0);
}

function statguide(step)
{
	HFcLoadTm.statguide(step);
}

function thisMovie(id)
{
	if (navigator.appName.indexOf("Microsoft") != -1) {
		return window[id];
	} else {
		return document[id];
	}
}

function jsAutoCommand(data)
{
	var f = thisMovie('gameContainer');
	if (f) {
		try {
			if(window.console) console.log(data);
			f.jsAutoCommand(data);
		} catch(e){
			if(window.console) console.debug(e);
		};
	}
}

function sendFeed(feed)
{
	feed = JSON.parse(feed);
	HFApp_sinawb.feed(feed);
	
}
function achieve(aid)
{
	HFApp_sinawb.achieve(aid);
}
function rank(rid, count)
{
	HFApp_sinawb.rank(rid, count);
}

function sendStaticFeed(type)
{
	var dt = {type:type};
	$.get('/feedapi/staticfeed', dt, function(data) {
		if (data && data.status > 0) {
			sendFeed(data.feed.data, false);
		}
	}, "json");
}
var minCtrWidth=856;
changeContentWidth();
  
function changeContentWidth(){
	var bodyWidth=$("body").width();
	if(bodyWidth<=minCtrWidth){
		var minCtrWidthCss = minCtrWidth+"px";
		$(".main").css("width",minCtrWidthCss);	
		//document.getElementById("testText").innerHTML=minCtrWidth;		
	}else{
		var ctrWidthCss = "100%";
		$(".main").css("width",ctrWidthCss);	
		//document.getElementById("testText").innerHTML=bodyWidth;
	}
	
	var containerWidth=$(".main").width();
	var conterWidthCss = (containerWidth) + "px" ;
	var maincontent = (containerWidth) + "px" ;
	var middle = (containerWidth-256) + "px";
	var noticeleft = (containerWidth-570) + "px";
	var boxleft = ((containerWidth-815)/2) + "px";
//	$("#main_content").css("width",conterWidthCss);
	$("#flashdiv").css("width",conterWidthCss);
	$("#gameContainer").css("width",conterWidthCss);
	$("#meunmiddle").css("width",middle);
	$("#notice1").css("left",noticeleft);
	$("#inviteBox").css("left",boxleft);
	$("#faq").css("left",boxleft);
	$("#payBox").css("left",boxleft);
	$("#helpBox").css("left",boxleft);
	
}

//为浏览器变化时加上侦听
$(window).resize(function(){
	WYX.Connect.resizeHeight(900);
	changeContentWidth();
});
</script>
{% if $smarty.const.APP_SERVER_TYPE == 1 %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33297048-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% /if %}
