<?php

$serverWords = array(
        "serverWord_10000"	=>	"test",
		"serverWord_100"	=>	"您同时开启了多个窗口，请刷新后重新进入游戏。",
        "serverWord_101"	=>	"网络超时，请点击按钮刷新页面。",
        "serverWord_102"	=>	"点击过快。",
        "serverWord_103"	=>	"已经初始化过人物角色了。",
        "serverWord_104"	=>	"初始化过人物角色失败。",
        "serverWord_105"	=>	"非好友，不能进行该操作",
        "serverWord_200"	=>	"对不起，操作失败，请稍候再来哦！",
        "serverWord_201"	=>	"您还没有学习这个合成术，不能合成哦！",
        "serverWord_202"	=>	"请选择正确的工作台来合成哦！",
        "serverWord_203"	=>	"请选择正确的合成术哦！",
        "serverWord_204"	=>	"材料不足哦！",
        "serverWord_205"	=>	"请选择正确的概率哦！",
        "serverWord_206"	=>	"宝石不足哦！",
        "serverWord_207"	=>	"金币不足哦！",
        "serverWord_208"	=>	"行动力不足哦！",
        "serverWord_209"	=>	"时间超出上限了，请选择正确的合成个数哦！",
        "serverWord_210"	=>	"请选择正确的工作台哦！",
        "serverWord_211"	=>	"合成术还没有完成，请稍候再来哦！",
        "serverWord_212"	=>	"您没有足够的沙漏来立即完成哦，请先购买吧！",
        "serverWord_213"	=>	"对不起，购买数据有误，请重新选择哦！",
        "serverWord_214"	=>	"请选择正确的订单哦！",
        "serverWord_215"	=>	"已接受订单已达上限哦，请先完成再来吧！",
        "serverWord_216"	=>	"订单已过期，请下次赶早哦！",
        "serverWord_217"	=>	"订单时间还没到，不能删除哦！",
        "serverWord_218"	=>	"订单已经接受，不能放弃哦！",
        "serverWord_219"	=>	"还没有新的订单哦！",
        "serverWord_220"	=>	"请选择正确的佣兵位置哦！",
        "serverWord_221"	=>	"佣兵位置已满，请先增加更多的位置吧！",
        "serverWord_222"	=>	"请选择正确的佣兵哦！",
        "serverWord_223"	=>	"请先卸下所有装备再来解雇吧！",
        "serverWord_224"	=>	"请选择正确的装备哦！",
        "serverWord_225"	=>	"佣兵等级还不恩那个使用这件装备，先去升级吧！",
        "serverWord_226"	=>	"佣兵职业不能使用这件装备哦！",
        "serverWord_227"	=>	"装备耐久度不足，不能装备哦！",
        "serverWord_228"	=>	"佣兵职业不能学习这个技能哦！",
        "serverWord_229"	=>	"请选择正确的技能学习哦！",
        "serverWord_230"	=>	"技能位置还没有解锁，不能学习哦！",
        "serverWord_231"	=>	"佣兵扩充位已达上限，不能再增加了哦！",
        "serverWord_232"	=>	"上阵人数超过上限了哦，请重新调整！",
        "serverWord_233"	=>	"阵型信息错误，请重新调整！",
        "serverWord_234"	=>	"佣兵等级不足，还不能解锁哦！",
        "serverWord_235"	=>	"您的等级不足，还不能使用该道具哦！",
        "serverWord_236"	=>	"您的行动力已满，不能再使用了！",
        "serverWord_237"	=>	"您已经学会该合成术，不能再使用了！",
        "serverWord_238"	=>	"角色血量已满，不能再使用了！",
        "serverWord_239"	=>	"您没有该道具了，请先购买吧！",
        "serverWord_240"	=>	"佣兵属性不能学习这个技能哦！",
        "serverWord_241"	=>	"该卷轴不是合成术卷轴，不能使用哦！",
        "serverWord_242"	=>	"技能不能重复学习哦！",

		//升级
        "serverWord_243"	=>	"经营等级不足，请先升级吧！",
        "serverWord_244"	=>	"声望不足哦！",

		//好友互动，加酒
        "serverWord_245"	=>	"请先成为好友后再来哦！",
        "serverWord_246"	=>	"好友酒馆已加满酒，请明天再来吧！",
        "serverWord_247"	=>	"一天只能帮好友加一次哦！",
        "serverWord_248"	=>	"您的酒还没有加满，快请好友来帮忙吧！",
        "serverWord_249"	=>	"免费的酒，一天只能使用一次哦！",
        "serverWord_250"	=>	"您的自宅等级不足，请先升级吧！",
        "serverWord_251"	=>	"您的主角等级不足，请先升级吧！",
		
		//佣兵派驻打工
        "serverWord_252"	=>	"请选择正确的派驻地点哦！",
        "serverWord_253"	=>	"神勇点不足哦！",
        "serverWord_254"	=>	"佣兵等级不足，还不能学习该技能哦！",
		"serverWord_255"	=>	"装备耐久度不足不能强化",
		"serverWord_256"	=>	"不是同类装备不能强化",
		"serverWord_257"	=>	"装备已强化到完美不能强化",
        "serverWord_258"    =>  "炼金熟练度等级不足",
        "serverWord_259"    =>  "佣兵等级不足，还不能传授技能",
        "serverWord_260"    =>  "你没有需要修理的装备！",

		//竞技场
        "serverWord_261"    =>  "您的等级还不能参加竞技场，请先升级吧！",
        "serverWord_262"    =>  "只能挑战竞技场列表中的对手！",
        "serverWord_263"    =>  "您没有剩余挑战次数可用了！",
        "serverWord_264"    =>  "您刚挑战过，请休息一下再来吧！",
        "serverWord_265"    =>  "由于时间久远，您所查看的战报已不存在哦！",
        "serverWord_266"    =>  "每天只能领取一次哦！",

		//vip
        "serverWord_267"    =>  "请先购买VIP之后再领取吧！",
        "serverWord_268"    =>  "您今天已经领取过了，请明天再来吧！",
        "serverWord_269"    =>  "请先购买VIP之后再强化吧！",

		//探险战斗
        "serverWord_301"	=>	"没有地图信息！",
        "serverWord_302"	=>	"不能直接进入该地图",
        "serverWord_303"	=>	"地图信息错误",
        "serverWord_304"	=>	"没有东西可以采集",
        "serverWord_305"	=>	"采集失败",
        "serverWord_306"	=>	"采集奖励获取失败",
        "serverWord_307"	=>	"该门在地图中不存在",
        "serverWord_308"	=>	"该门不通往指定地图",
        "serverWord_309"	=>	"进入该副本的条件尚未满足",

        "serverWord_321"	=>	"战斗初始化失败-本方数据空",
        "serverWord_322"	=>	"战斗初始化失败-敌方数据空",
        "serverWord_323"	=>	"体力不足时不能战斗",

		//传送门
        "serverWord_333"	=>	"您的该传送门尚未激活，还不能使用！",
        "serverWord_334"	=>	"该副本不能使用传送门！",
        "serverWord_335"	=>	"传送石不足哦！",

        //任务
        "serverWord_400"	=>	"任务条件未达成",
        "serverWord_401"	=>	"没有任务可以完成",
        "serverWord_402"	=>	"任务已经刷新，请刷新页面重新进入",
        "serverWord_403"	=>	"该任务不可用任务符直接完成",
        "serverWord_404"	=>	"任务符数量不够直接完成任务，请去商店购买任务符",
        //礼物
        "serverWord_500"	=>	"礼物处理失败",
        "serverWord_501"	=>	"礼物处理id为空",
        "serverWord_502"	=>	"礼物处理id非法",
        "serverWord_503"	=>	"礼物处理uid非法",
        "serverWord_504"	=>	"请选择礼物",
        "serverWord_505"	=>	"最多选择三个礼物",
        "serverWord_506"	=>	"该礼物不存在或已经下线",
        "serverWord_507"	=>	"等级不足",
        "serverWord_508"	=>	"今天已经发布过愿望了。",
        "serverWord_509"	=>	"该愿望已经过期了。",
        "serverWord_510"	=>	"该礼物愿望不存在。",
        "serverWord_511"	=>	"请选择好友",
        "serverWord_512"	=>	"每天最多只可以发送20次礼物给好友",
        //交互侵略
        "serverWord_600"	=>	"初始化数据不正确",
        "serverWord_601"	=>	"侵略保护已经开启了",
        "serverWord_602"	=>	"被占领中/被攻击中不可以开启保护哦",
        "serverWord_603"	=>	"该好友未被占领，不可收税。",
        "serverWord_604"	=>	"未占领该好友，不可收税。",
        "serverWord_605"	=>	"未占领该好友，不可收税。",
        "serverWord_606"	=>	"好友炼金熟练度未到5级，不可侵略！",
        "serverWord_607"	=>	"收税时间未到",
        "serverWord_608"	=>	"对方开启侵略保护，不能侵略",
        "serverWord_609"	=>	"攻击后2小时保护期，不能侵略",
        "serverWord_610"	=>	"10级以下新手保护中，不能侵略",
        "serverWord_611"	=>	"等级相差过大，不能侵略",
        "serverWord_612"	=>	"佣兵不足，不能侵略",
        "serverWord_613"	=>	"没有被侵略，不能反抗",
        "serverWord_614"	=>	"好友没有被侵略，不需要援助",
		"serverWord_615"	=>	"该玩家正在被攻占中，暂时无法侵略哦",

		//自动回复
		"serverWord_700"	=>	"已达上限无需再补充",
        //活动礼包
        "serverWord_701"	=>	"未达到条件不能领奖",
 		"serverWord_702"	=>	"所有奖励已领取完",
		"serverWord_703"	=>	"该奖励已领取，请明日再领取",
		"serverWord_704"	=>	"活跃度不足，不能领取",
		//体力
		"serverWord_705"	=>	"体力补充次数已达上限",
		//强化
		"serverWord_706"	=>	"装备强化等级不能超过主角等级",
		"serverWord_707"	=>	"幸运石不足",
		"serverWord_708"	=>	"精炼石不足",
		"serverWord_709"	=>	"已自动刷新,无需手动",
		"serverWord_710"	=>	"交付订单已达上限",
		"serverWord_711"	=>	"钥匙不足不能开启",
		"serverWord_712"	=>	"今天的宝箱已经开启过",
		"serverWord_713"	=>	"没有宝箱不能开启",
		"serverWord_714"	=>	"强化冷却中，稍后再来",

		"serverWord_731"	=>	"您还不是黄钻用户，不能领取该礼包哦",
		"serverWord_732"	=>	"对不起，礼物领取失败，请稍候再来哦",
		"serverWord_733"	=>	"对不起，礼物领取失败，请稍候再来哦",
		"serverWord_734"	=>	"您今天已经领取过该奖励了哦，请明天再来吧",
		"serverWord_735"	=>	"您已经领取过该新手礼包哦",
		

);

