<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>炼金大冒险</title>
{% if $platform == "sinaweibo" %}
<link href="{%$staticUrl%}/alchemy/main_wb.css?v=1.03" rel="stylesheet" type="text/css" />
{% else %}
<link href="{%$staticUrl%}/alchemy/main_kx_2012070101.css?v=1.03" rel="stylesheet" type="text/css" />
{% /if %}
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/hf-report.js?v=1.3.js" type="text/javascript"></script>
<script src="{%$staticUrl%}/js/hf-app.js?v=1.0.js" type="text/javascript"></script>
<style type="text/css">
<!--
body{overflow-x:hidden;}
a img,:link img,:visited img {border:0 none;}
object#swfcontent {display:inline;}
.box {border:1px solid #CCCCCC;}
#notice li{padding-bottom:4px;}
-->
</style>
</head>
<body style="height:1500px;padding-left:150px;">
{% if $platform == "sinaweibo" %}
	<body style="margin: auto; display: block; width:815px;">
	<div class="main" style="height:688px;">
	{%include file="menu_sinawb1.phtml"%}
	<div style="clear:both;"></div>
<!--		<div id="main_content" style="position:relative;background-color:#000000;background-image:url({%$staticUrl%}/alchemy/image/install-bg3.jpg);height:600px;">-->
{% else %}
<body>
	<div class="main" style="height:688px;">
	{%include file="menu.phtml"%}
	<div style="clear:both;"></div>
		<div id="main_content" style="position:relative;background-color:#000000;background-image:url({%$staticUrl%}/alchemy/image/install-bg3.jpg);width:815px;height:600px;">
{% /if %}
	<div id="loadingdiv" style="position:absolute;left:350px;top:350px;color:#FFFFFF;"><img src="{%$staticUrl%}/alchemy/image/common/loading1.gif" /><br/>加载中......</div>
		<div id="pause" style="position:absolute;left:180px;top:130px;display:none;"><img src="{%$staticUrl%}/alchemy/image/pause.png" style="width:465px;height:218px;cursor:pointer;" onclick="showFlash();" /></div>
		<div id="flashdiv" style="position:absolute;"><div id="flashContainer"></div></div>
		<script src="{%$staticUrl%}/js/swfobject.js" type="text/javascript"></script>
		<script type="text/javascript">
			var VIEWER_ID = {%$uid%};
			var OWNER_ID = VIEWER_ID;

			HFcLoadTm.flashloadlog(13);
			function getCookie(name) {
				var arr = document.cookie.match(new RegExp('(^| )'+name+'=([^;]*)(;|$)'));
				if(arr != null) return unescape(arr[2]); return null;
			}
			var hf_skey = getCookie('hf_skey');
			if (hf_skey) {
				var vars = {
					interfaceHost:"{%$hostUrl%}/",
					staticHost:"{%$staticUrl%}/{%$swf_ver%}/",
					initInterface: "{%$hostUrl%}/api/initswfwatch?v=2012082201",
					localWords: "{%$staticUrl%}/{%$swf_ver%}/data/localeWord.txt?v=v2012082201",
					initUi: "{%$staticUrl%}/{%$swf_ver%}/loading1.swf?v=2011040701",
					tipsStr: '{%$tipsStr%}',
					piantou: "{%$piantou%}",
					createUrl: "{%$createUrl%}",
					createModule: "{%$createModule%}",
					trackFlag:"{%$trackFlag%}",
					snsType:"{%$platformSns%}"
				};
	        	var params = {
	    	        	allowScriptAccess:"always",
	    	        	menu:"false",
	    	        	wmode:"window",
	    	        	allowFullScreen:"true",
	    	        	bgcolor:"#000000",
	    	        	align:"middle",
	    	        	quality:"high"
		    	};
	        	var attrs = {id:"gameContainer",name:"gameContainer" };
	        	
	        	swfobject.embedSWF("{%$staticUrl%}/{%$swf_ver%}/v2012110901/MagicLoader.swf?v=20111111v1", "flashContainer",  815, "600", "10.0", "{%$staticUrl%}/expressInstall.swf", vars, params, attrs, checkFlashable);

		        hideLoading();
		    } else {
	        	var html = '<div style="padding-top:50px;color:red;font-size:14px;text-align:center;">检测到您的浏览器没有开启或接收Cookie！请尝试开启后，重新进入。</div>';
	        	$('#flashContainer').html(html);
	        	HFcLoadTm.nocookie();
	        }

			function checkFlashable(res) {
				if (!res.success) {
					var strhtml = '您没有安装Adobe Flash Player，或者Flash版本过低，建议安装10.0以上版本。<br/>请点击<a href="http://get.adobe.com/cn/flashplayer/" target="_blank">这里</a>进行安装。';
					$('#loadingdiv').css('left', '100px').css('top', '250px').css('color', 'red').html(strhtml);
					HFcLoadTm.noflash();
				}
			}

			function hideLoading()
			{
				$('#loadingdiv').hide();
				HFcLoadTm.flashStartLoad();
				if (window.console && console.debug) {
					console.debug('startload');
				}
			}

			function hideFlash()
			{
				$('#flashdiv').css('left', -9999);
				$('#pause').show();
			}

			function showFlash()
			{
				$('#flashdiv').css('left', 0);
				$('#pause').hide();
			}

			function enterGame()
			{
				$('#flashdiv').css('left', 0);
				$('#pause').hide();
				if ($('#faq')) {
					 $('#faq').hide();
					 $('#faq').height(600);
				}
			}

			function loadCompleted()
			{
				HFcLoadTm.flashFinishLoad();
				if (window.console && console.debug) {
					console.debug('endload');
				}

				var img = new Image();
				img.src = "{%$hostUrl%}/api/initfightassist";
				return;
			}

			function flashload_log(id)
			{
				HFcLoadTm.flashloadlog(id);
				if (window.console && console.debug) {
					console.debug('flashLoadLog');
				}
			}
			//setTimeout((function(){loadCompleted();}) , 10000);
	        $('#loadingdiv').hide();
		</script>
	</div>
</div>
{% if $platform == "sinaweibo" %}
	{%include file="footer_sinawb1.phtml"%}
{% else %}
	{%include file="footer.phtml"%}
{% /if %}
{% if $devtype != 1 && $uid != 10020 %}
{%include file="watch/tools.phtml"%}
{% elseif $userName == "nick" %}
{%include file="watch/tools.phtml"%}
{% /if %}
</body>
</html>