{%include file="hapyfishadmin/header.phtml"%}
<style type="text/css">
    <!--
    table{font-size:14px;border-collapse: collapse;border-spacing: 0;empty-cells: show;}
    th, td {border: 1px solid #B1CBE2;}
    th{background-color: #D5E7F3;}
    td{padding:2px;}
    .odd{background-color: #EAF2F5;}
    .total{font-weight:bold;}

    -->
</style>
<h1>后台管理</h1>
<ul id="nav">
    <li><a href="{%$baseUrl%}/swhadmin">首页</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/timegift">时间礼包管理</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/levelgift">等级礼包管理</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/sevengift">七天礼包管理</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/package">礼包管理</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/daliytask">日常任务</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/guild">公会</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/activity">活动礼包</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/activitycdkey">活动cdkey生成</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/loadinggift">loading活动礼包</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/everysignnotice">每日趣闻</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/everysignlaba">每日签到 拉霸奖励</a></li>
    <li><a href="{%$baseUrl%}/swhadmin/everysignfiveandseven">每日签到 5日7日奖励</a></li>
    <li>当前登录者：{%$adminName%}</li>
</ul>

<div id="container">
    <strong>每日签到 5日7日奖励</strong>
      注：1为5日礼包 2为7日礼包
    <div id="divedit">
        <table >
            <tr>
                <th>类型</th><th>奖励</th><th>操作</th>
            </tr>
            {% foreach from=$list item=data %}
            <tr>
                <td><input id="actitivty_list" value="{%$data.id%}" size=38 /></td>
                <td><input id="actitivty1_{%$data.id%}" value="{%$data.award%}" size=38 /></td>
                <td><input type="button"  onclick="add({%$data.id%});" value="修改"/></td>
            </tr>
            {% /foreach  %}
        </table>
        <input type="button" onclick="rest()" value="重置5日7日礼包缓存">
    </div>
</div><!--/#container-->
<script type="text/javascript">
    function rest(){
        $.ajax({
            type: 'POST',
            url: '/swhadmin/everysignfiveandsevenrest',
            data: {'type':0},
            dataType: 'text',
            success: function(resp){
                alert('操作成功');
                location.reload(true);  
            },
            error: function(resp){
            },
            complete: function(resp){
            }
        });
    }
    
    function add(id) {
        var award = $("#actitivty1_"+id).val();
        $.ajax({
            type: 'POST',
            url: '/swhadmin/everysignfiveandsevenawardadd',
            data: {'id':id, 'award':award},
            dataType: 'text',
            success: function(resp){
               alert('操作成功');
                location.reload(true);  
            },
            error: function(resp){
            },
            complete: function(resp){
            }
        });	
    }
</script>
{%include file="hapyfishadmin/footer.phtml"%}