{%include file="hapyfishadmin/header.phtml"%}
	<h1>{%$appTitle%}后台管理（{% if $smarty.const.APP_SERVER_TYPE==3 %}开发服{% elseif $smarty.const.APP_SERVER_TYPE==2%}测试服{% else %}***正服***{% /if %}）</h1>
	{%include file="hapyfishadmin/nav.phtml"%}

	<div id="container">
		<strong>服务器信息：<div style="color:red">{% if $smarty.const.APP_SERVER_TYPE==3 %}开发服{% elseif $smarty.const.APP_SERVER_TYPE==2%}测试服{% else %}***正服***{% /if %}</div></strong>
		<br/>平台编号：{%$smarty.const.PREX_APC%}
		<br/>应用appId：{%$smarty.const.APP_ID%}
		<br/>应用名称：{%$appTitle%}
		<br/>应用地址：http://apps.renren.com/{%$smarty.const.APP_NAME%}/
		<br/>模拟登录地址：{%$smarty.const.HOST%}/watch?uid=XXX
	</div><!--/#container-->

{%include file="hapyfishadmin/footer.phtml"%}