<div class="main">
	<div style="height:669px;width:794px;background:url('http://testalchemystatic.happyfish001.com/weibo/alchemy/image/helpbg.jpg');padding:10px;border-right:1px solid #5e3929;border-bottom:1px solid #5e3929;">
		<div style="height:691px;">
		<div style="margin-left:7%;"></div>
	
	<div id="selFriend" style="width:710px; height:670px;position:absolute;left:27px;top:20px;display:table;">
    <div style="width:710px; height:50px; ">
    <a id="mnuInviteCls" href="javascript:void(0);"><div style="width:50px; height:50px; display:block; float:right;"></div></a>
    </div>
    <div id="divWyxFrame" style="padding-left: 55px;padding-top: 30px;width:710px; height:670px; background-repeat:repeat-y;">
    </div>
    <div style="width:710px; height:50px;"></div>
	</div>
	
		</div>
	</div>
</div>

<script type="text/javascript">

function initInvite(show)
{
{% if $smarty.const.APP_ID==3507232293 %}
	//$("#divWyxFrame").html('<iframe src="http://game.weibo.com/home/widget/selector?&target=self&appId=401380203&mode=naf&action=http%3A%2F%2Ft.happyfishgame.com.cn%2Finvite%2Fsend&excludeIds=&pageSize=20&content=%E6%B2%99%E6%BB%A9%E7%8B%82%E6%AC%A2%E3%80%81%E6%B5%B7%E5%B2%9B%E5%AF%BB%E5%AE%9D%EF%BC%81%E5%85%A8%E5%9B%BD%E7%AC%AC%E4%B8%80%E6%AC%BE%E6%B5%B7%E5%B2%9B%E6%A8%A1%E6%8B%9F%E7%BB%8F%E8%90%A5%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%B8%A6%E4%BD%A0%E4%B9%90%E4%BA%AB%E6%B5%AA%E6%BC%AB%E6%B5%B7%E5%B2%9B%E7%94%9F%E6%B4%BB%EF%BC%8C%E4%B8%80%E8%B5%B7%E6%9D%A5%E7%8E%A9%E5%90%A7&callback=http%3A%2F%2Fgame.weibo.com%2Fhappyisland" width="95%" height="470px" frameborder="no"></iframe>');
	$("#divWyxFrame").html('<div class="requestForm"><form method="post" action="http://game.weibo.com/home/widget/requestForm" id="createToolFriend" target = "friendSelector"><input type="hidden" name="target" value="self" /><input type="hidden" name="appId" value="3507232293" /><input type="hidden" name="modes" value="all,af,naf" /><input type="hidden" name="selectedMode" value="naf" /><input type="hidden" name="action" value="http://acwb.happyfishgame.com.cn/invitesinawb/send" /><input type="hidden" name="excludedIds" value="" /><input type="hidden" name="pageSize" value="16" /><input type="hidden" name="content" value="经典回合制角色扮演游戏霸气回归！以我手中剑，心中勇气，领千万英雄，屠尽恶龙与邪恶，还世界爱与和平！" /><input type="hidden" name="callback" value="http://game.weibo.com/dragons/" /></form><iframe width="670px" height="500px" frameborder="0" src="" name="friendSelector" scrolling="no" id="friendSelector"></iframe></div>');
{% else %}
	//$("#divWyxFrame").html('<iframe src="http://game.weibo.com/home/widget/selector?&target=self&appId=1142074347&mode=naf&action=http%3A%2F%2Fweibo-t1.happyfish001.com%2Finvite%2Fsend&excludeIds=&pageSize=12&content=%E6%B2%99%E6%BB%A9%E7%8B%82%E6%AC%A2%E3%80%81%E6%B5%B7%E5%B2%9B%E5%AF%BB%E5%AE%9D%EF%BC%81%E5%85%A8%E5%9B%BD%E7%AC%AC%E4%B8%80%E6%AC%BE%E6%B5%B7%E5%B2%9B%E6%A8%A1%E6%8B%9F%E7%BB%8F%E8%90%A5%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%B8%A6%E4%BD%A0%E4%B9%90%E4%BA%AB%E6%B5%AA%E6%BC%AB%E6%B5%B7%E5%B2%9B%E7%94%9F%E6%B4%BB%EF%BC%8C%E4%B8%80%E8%B5%B7%E6%9D%A5%E7%8E%A9%E5%90%A7&callback=http%3A%2F%2Fgame.weibo.com%2Fisland_dev" width="95%" height="470px" frameborder="no"></iframe>');
	$("#divWyxFrame").html('<div class="requestForm"><form method="post" action="http://game.weibo.com/home/widget/requestForm" id="createToolFriend" target = "friendSelector"><input type="hidden" name="target" value="self" /><input type="hidden" name="appId" value="2935246284" /><input type="hidden" name="modes" value="all,af,naf" /><input type="hidden" name="selectedMode" value="naf" /><input type="hidden" name="action" value="http://acwb.happyfishgame.com.cn/invitesinawb/send" /><input type="hidden" name="excludedIds" value="" /><input type="hidden" name="pageSize" value="16" /><input type="hidden" name="content" value="经典回合制角色扮演游戏霸气回归！以我手中剑，心中勇气，领千万英雄，屠尽恶龙与邪恶，还世界爱与和平！" /><input type="hidden" name="callback" value="http://game.weibo.com/dragons/" /></form><iframe width="670px" height="500px" frameborder="0" src="" name="friendSelector" scrolling="no" id="friendSelector"></iframe></div>');
{% /if %}

	document.getElementById("createToolFriend").submit();
	if ('1' == show) {
		showInvite();
	}
	
}

initInvite();
</script>
