<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>vip 介绍</title>
<style type="text/css">
<!--
body {
	margin: auto;
	margin-top: 0px;
	margin-right: auto;
	margin-bottom: 0px;
}
-->
</style></head>

<body>
<div  style="width:960px; margin:auto" >
    <div style="height:236px;"><a href="#"><img src="{%$staticUrl%}/alchemy/image/vip/vip--01.gif" border="0"/></a> </div>
  <div style="height:114px;"><img src="{%$staticUrl%}/alchemy/image/vip/vip--02.gif" /></div>
    <div style="height:175px;"><img src="{%$staticUrl%}/alchemy/image/vip/vip--03.gif" /></div>
    <div style="height:169px;"><img src="{%$staticUrl%}/alchemy/image/vip/vip--04.gif" /></div>
  <div style="height:99px;"><img src="{%$staticUrl%}/alchemy/image/vip/vip--05.gif" /></div>
    <div style="height:495px;"><img src="{%$staticUrl%}/alchemy/image/vip/vip--06.gif" /></div>
    <div style="height:137px;"><a href="#"><img src="{%$staticUrl%}/alchemy/image/vip/vip--07.gif" border="0" /></a></div>
</div>
</body>
</html>
