<div style="width:auto; height:88px">
<div id="meunfrist" ></div>
<div id="meunmiddle">
<div style="width:600px;float:right;">
    	<div class="menu">
    	<ul>
			<li id="invite" alt="邀请好友"><a href="javascript:void(0);"></a></li>
        	<li id="pay" alt="Q点充值 " title="Q点充值"><a href="javascript:void(0);"></a></li>
        	<li id="paysel" alt="Q点查询 " title="Q点查询"><a href="javascript:void(0);"></a></li>
        	<li id="help" alt="黄钻特权"><a href="{%$staticUrl%}/alchemy/html/hz/hz.html" target="_blank"></a></li>
        	<li id="forum" alt="玩家论坛" title="暂未开通"><a href="http://bbs.open.qq.com/forum.php?mod=forumdisplay&action=list&fid=920" target="_blank"></a></li>
        	<li id="faqm" alt="问题反馈 "><a href="javascript:void(0);" onclick="showfaq();"></a></li>
        	
    	</ul>
    	</div>
    	<div id="notices"></div>
    	</div>
    </div>
    <div id="meunright"></div>
	<div style="clear:both;">
	</div>
{% if $showNotice == true %}
<div id="notice1" style="position:absolute;left:260px;top:65px;width:520px;height:16px;overflow:hidden;">
<ul>
{% foreach from=$notice item=data %}
<li>{%if $data.link%}<a href="{%$data.link%}" target="_blank">[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}</a>{%else%}[{%$data.create_time|date_format:"%Y-%m-%d"%}]  {%$data.title%}{%/if%}</li>
{% /foreach %}
</ul>
<script type="text/javascript">
function autoScroll(obj)
{
$(obj).find("ul:first").animate({
	marginTop:"-16px"
	},500,function(){
		$(this).css({marginTop:"0px"}).find("li:first").appendTo(this);
	});
}
$(document).ready(function(){
	setInterval('autoScroll("#notice")',10000)
});
</script>

</div>
{% /if %}
</div>

