<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="{%$staticUrl%}/alchemy/feed.css?v=1.04" rel="stylesheet" type="text/css" />
<script src="{%$staticUrl%}/js/jquery-1.4.3.min.js" type="text/javascript"></script>
<title>炼金客服</title>
<style type="text/css">
body{font:12px/1.5 Arial, Helvetica, sans-serif; background:#ffffff; color:#666;}
body,ul,li{margin:0; padding:0;}
a{text-decoration:none; color:#666666;}
img{border:none;}
img,input{vertical-align:middle;}
td{border-bottom:#d5e7f3 1px solid ;}
ul li{list-style:none;}
</style>
</head>
<body>
<!-- ClickTale Top part -->
<script type="text/javascript">
var WRInitTime=(new Date()).getTime();

</script>
<!-- ClickTale end of Top part -->
<div class="z-m z-w74" style="margin-top:20px;">
<div class="b8">
	<div class="height8"></div>
	<div>
		
    	<a href="{%$hostUrl%}/faq/index?uid={%$uid%}">
    		<div class="tab_p7a" style="font-weight:bold;">提交问题</div>
    	</a>
    	<div class="w20"></div>
    	<a href="{%$hostUrl%}/faq/myfaq?uid={%$uid%}">
    	<div class="tab_p6a" style="font-weight:bold;">我的问题</div>
    	</a>
    	<div class="w480"></div>
  	</div>
  	<ul class="p6">
		
	</ul>
  	
    <div class="height4"></div>
    

    
  	<div style="clear:both;"></div>
  	<div style="width:740px;height:500px; overflow-y:auto;">
  	<form  method="post" action="{%$hostUrl%}/faq/delete" name="UForm" enctype="multipart/form-data" id="check">
<table width="720" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#eeeeee" style="table-layout:fixed;" >
	<tr >
<td width="20" align="left" bgcolor="#D5E7F3" ></td>
    <td  align="left" bgcolor="#D5E7F3">标题</td>
    <td  align="left" bgcolor="#D5E7F3" width="106">处理状态</td>
    <td width="130" align="left" bgcolor="#D5E7F3">提交日期</td>
    </tr>
    {%if $faq%}
    {%foreach from=$faq item=data%}
  	<tr >
    <td align="left" bgcolor="#FFFFFF" ><input type="checkbox" id="{%$data.id%}" name="ids[]" value="{%$data.id%}"></td>
    <td align="left" bgcolor="#FFFFFF" class="p1234" style="overflow:hidden;"><a href="{%$hostUrl%}/faq/showdetail?id={%$data.id%}&uid={%$uid%}">{%$data.title|truncate:90:"...":true%}</a></td>
    <td align="left" bgcolor="#FFFFFF" class="p1234" {% if $data.status == 1%} style="color:#ff0000;" > 已回复{%else%} >处理中{%/if%}</td>
    <td align="left" bgcolor="#FFFFFF" class="color666">{%$data.create_time|date_format:"%Y-%m-%d %H:%M:%S"%}
</td>
    </tr>
    {%/foreach%}
    {%/if%}
    <tr bgcolor="#D5E7F3"><td colspan="4">
    	<input type="hidden" name="uid" value="{%$uid%}">
    	<input type="checkbox" id="delChkbox">全选
    	<input type="submit" class="btn_3" value="删除" id="qstDelBtn">
    </td></tr>
</table>
</form>
</div>
<div class="height4"></div>
<div class="page">  </div>
<div class="height8"></div>
<div class="height8"></div>
</div>
</div>
<!-- ClickTale Bottom part -->
<div id="ClickTaleDiv" style="display: none;"></div>
{% if $smarty.const.APP_SERVER_TYPE == 1 %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33297048-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% /if %}
<script>
//jQ实现全选全不选
$(function(){
    var _jq_chk = $('#delChkbox:checkbox');
    var _jqitems = $(':checkbox[name=ids[]]');
    var _rows = $('#check tr td');
    
    //全选与全不选一体实现
    _jq_chk.click(function(){
		//列表中选框和全选选框统一状态
        _jqitems.add(_jq_chk).attr('checked', this.checked);
    });
	
    //选框的点击事件
    _jqitems.click(function(e){
        //阻止冒泡,避免行点击事件中,直接选择选框无效
        e.stopPropagation();
		//判断选中个数与实际个数是否相同,以确定全选/全不选状态
        _jq_chk.attr('checked', _jqitems.size() == _jqitems.filter(':checked').size());
    });
	
    //点选行时选中行内的checkbox
    _rows.bind({
        mouseenter: function(){
            $(this).addClass('hover');
        },
        mouseleave: function(){
            $(this).removeClass('hover');
        }
		//点选
//        click: function(){
//			//行内点击时,行内的选框状态为原状态取反
//            $(this).find(':checkbox').attr('checked', !$(this).find(':checkbox').get(0).checked)
//			//判断选中个数与实际个数是否相同,以确定全选/全不选状态
//            _jq_chk.attr('checked', _jqitems.size() == _jqitems.filter(':checked').size());
//        }
    });
});
</script>
</body>
